CREATE TABLE IF NOT EXISTS pools (
  id SERIAL PRIMARY KEY,
  pool_address VARCHAR(64) NOT NULL UNIQUE,
  metadata JSONB,
  token_base VARCHAR(128),
  token_quote VARCHAR(128),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_positions (
  wallet VARCHAR(64) NOT NULL PRIMARY KEY,
  positions JSONB,
  fetched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);