CREATE TABLE IF NOT EXISTS pools (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pool_address VARCHAR(64) NOT NULL UNIQUE,
  metadata JSON NULL,
  token_base VARCHAR(128) NULL,
  token_quote VARCHAR(128) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_positions (
  wallet VARCHAR(64) NOT NULL PRIMARY KEY,
  positions JSON NULL,
  fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
